### ISSUE TITLE
marquee tag Deprecated

### ISSUE THREAD

**Issue by NoreenNaz1234** [sana-ishaque/may-14-assignment#1]
(example of MDN) Deprecated
This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

https://github.com/sana-ishaque/may-14-assignment/blob/dfbad4cbfedb34ec288cda35f97a001a105c7f1a/index.html#L19

as you work with marquee tag... DO NOT USE THIS. ap is k replace main animation use kr skti h. here is link
 https://daneden.github.io/animate.css/
ap isko download kren then apny folder main rkhen aur index main isko link krwa den. for example apko para main animation chye to ap para main class put kr den jo b apko animation chye

**Comment by sana-ishaque** [comment]
thnaks for sharing this app. Miss sara told in last class that it's okay to use marquee tag if i am not wrong. also i couldn't find animation like that of marquee in the suggested app..
