### ISSUE TITLE
Background opacity 

### ISSUE THREAD

**Issue by NoreenNaz1234** [sana-ishaque/may-14-assignment#14]
https://github.com/sana-ishaque/may-14-assignment/blob/0c67ce22b518b7d0ddbba59778db6fdcf9902f12/style.css#L65

ap isko dkhen apko kia fark nazar aega apni web dkhen aur mockup dkhen.

**Comment by sana-ishaque** [comment]
it's transparent when header reaches top, changing header's opacity is making it transparent overall. i did find it on google and found jquery involved for that scrolling transparency. if u can pls suggest anything.
